[project]
name = "cookiecutter-rt-pkg"
description = "RT pkg template - don't try to install this as package, use it as cruft template"
license = {file = "LICENSE"}
authors = [
    {name = "Reef Technologies", email = "opensource@reef.pl"},
]
requires-python = "==3.14.*"

dependencies = [
    "cruft==2.16.0",
    "ruff==0.15.8",
    "codespell==2.4.2",
]

dynamic = [
    "version",
]

[tool.ruff]
line-length = 120
exclude = [
    "\\{\\{cookiecutter.package_name\\}\\}",
]

[tool.ruff.lint]
select = [
    "D",
    "E", "F", "I", "UP",
    "TC005",
]
ignore = [
    "E501",  # checked&fixed by ruff format
    "D100", "D105", "D107", "D200", "D202", "D203", "D205", "D212", "D400", "D401", "D415",
    "D101", "D102", "D103", "D104", # TODO remove once we have docstring for all public methods
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test/**" = ["D", "F403", "F405"]

[tool.codespell]
skip = "*.min.js,uv.lock"
ignore-words-list = "datas"

[tool.commitizen]
version_provider = "scm"
annotated_tag = true
tag_format = "v$version"
changelog_file = "{{cookiecutter.package_name}}/docs/3rd_party/cookiecutter-rt-pkg/CHANGELOG.md"
changelog_incremental = true
changelog_merge_prerelease = true
update_changelog_on_bump = true

[tool.mypy]

[[tool.mypy.overrides]]
module = [
    "nox",
    "pytest",
]
ignore_missing_imports = true

[tool.uv]
exclude-newer = "14 days"
