name: Run linter and tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox 'pdm>=2.12,<3'
      - name: Run linters
        run: nox -vs lint
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ env.PYTHON_DEFAULT_VERSION }}{% endraw %}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade 'nox==2024.3.2' 'pdm==2.13.2'
      - name: Run unit tests
        run: nox -vs test
