name: Continuous Integration

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.12"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
# COOKIECUTTER{%- raw %}
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
          cache-dependency-path: 'uv.lock'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ env.PYTHON_DEFAULT_VERSION }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: ${{ env.PYTHON_DEFAULT_VERSION }}-uv-
# COOKIECUTTER{%- endraw %}
      - name: Install dependencies
        run: python -m pip install --upgrade nox uv
      - name: Run linters
        run: nox -vs lint
  test:
    timeout-minutes: 10
# COOKIECUTTER{%- raw %}
    runs-on: ${{ matrix.os }}
# COOKIECUTTER{%- endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.12"]
        # COOKIECUTTER{%- if cookiecutter.is_django_package == "y" %}
        django-version: ["3.2", "4.2"]
        # COOKIECUTTER{%- endif %}
# COOKIECUTTER{%- raw %}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'uv.lock'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ matrix.python-version }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: ${{ matrix.python-version }}-uv-
      - name: Install dependencies
        run: python -m pip install --upgrade 'nox==2024.3.2' uv
      - name: Run unit tests
        run: nox -vs test
# COOKIECUTTER{%- endraw %}
