name: Continuous Integration

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-uv-nox
      - name: Run linters
        run: uvx nox -vs lint

  test:
    timeout-minutes: 10
    {% raw %}
    runs-on: ${{ matrix.os }}
    {% endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version:
        {% for version in cookiecutter.python_versions.split(",") | map("trim") %}
          - "{{ version }}"
        {% endfor %}
        {% if cookiecutter.django_versions %}
        django-version:
        {% for version in cookiecutter.django_versions.split(",") | map("trim") %}
          - "{{ version }}"
        {% endfor %}
        {% endif %}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-uv-nox
      - name: Run unit tests
        run: uvx nox -vs "test-{% raw %}${{ matrix.python-version }}{% endraw %}{% if cookiecutter.django_versions %}(django='{% raw %}${{ matrix.django-version }}{% endraw %}'){% endif %}"
