version: 2
updates:
  - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    directory: /
    open-pull-requests-limit: 0
  - package-ecosystem: "docker"
    schedule:
      interval: "weekly"
    directory: /
    open-pull-requests-limit: 0
