name: Continuous Integration

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-uv-nox
      - name: Run linters
        run: nox -vs lint
  check_crufted_project:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cruft_config: ["default", "django"]
    env:
      CRUFT_TESTED_CONFIGS: ${{ matrix.cruft_config }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-uv-nox
      - name: Run checks on project created from template
        run: nox -vt crufted_project
