name: Continuous Integration

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.12"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            **/pyproject.toml
            **/pdm.lock
      - name: Install dependencies
        run: python -m pip install --upgrade nox pdm
      - name: Run linters
        run: nox -vs lint
  check_crufted_project:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cruft_config: ["default", "django"]
    env:
      CRUFT_TESTED_CONFIGS: ${{ matrix.cruft_config }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install --upgrade nox pdm
      - name: Run checks on project created from template
        run: nox -vt crufted_project
